name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 19
targetAbi: "10.10.6.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |-
  - Improved null handling for tvdb provider (#207) @systemcrash

  ### New features and improvements ###
  - Added missing season type 'alttwo' (#200) @Kianda

  ### Bug Fixes ###
  - Handle empty ParentIndexNumber (#209) @Shadowghost
