name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 21
targetAbi: "10.11.5.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "MoviesAndShows"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |-
  - Fix incorrect offset in birth and death dates (#214) @theguymadmax
  - Add season number fallback (#222) @ivanjx

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to v10 (#223) @[renovate[bot]](https://github.com/apps/renovate)
