name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 15
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |2-
  ### Bug Fixes ###
  - Set ContentRatings list to be nullable (#171) @scampower3
