name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 14
targetAbi: "10.9.9.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |2-
  ### Major features and improvements ###
  - Add Movie support (#164) @scampower3

  ### New features and improvements ###
  - Add support for movie and season for check for metadata update task. Add additional configurations. (#169) @scampower3
  - Season support with extended season client (#165) @scampower3
  - Add Tvdb Collection Ids (#162) @scampower3

  ### Bug Fixes ###
  - Fix movie remote id ProviderName  (#167) @scampower3
  - Skip Characters with person name is null / Handle null RemoteIds (#160) @scampower3
  - Add season url (#161) @scampower3
  - Add option to fallback to original language (#156) @scampower3

  ### Dependency updates ###
  - Update dependency Tvdb.Sdk to v4.7.10 (#158) @renovate
