name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 13
targetAbi: "10.9.5.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |-
  - Simplify Series Handling in Missing Episode Provider (#151) @scampower3
  - Use official instead of default (#149) @scampower3

  ### Bug Fixes ###
  - Fix Specials being added during season refresh when IncludeMissingSpecials is disabled (#152) @scampower3
  - Set DeleteFileLocation = false (#153) @scampower3
  - Fix Language mapping for unique cases (#145) @scampower3
  - Get season id according to selected display order. (#147) @scampower3
