name: "TheTVDB"
guid: "a677c0da-fac5-4cde-941a-7134223f14c8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-tvdb.png"
version: 16
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Get TV metadata from TheTvdb"
description: >
  Get TV metadata from TheTvdb

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Tvdb.dll"
  - "Tvdb.Sdk.dll"
changelog: |-
  - Fix 10.10 nullability (#186) @crobibero

  ### New features and improvements ###
  - Remove All Missing Episodes On Refresh (#176) @scampower3
  - Add original countries of series or movies as tags (#184) @scampower3
  - Move to IExternalUrlProvider (#179) @scampower3
  - Add people provider  (#173) @scampower3

  ### Bug Fixes ###
  - Only generate url when there is externalId for season (#190) @scampower3
  - Update Season provider to use SeriesDisplayOrder field (#180) @scampower3
  - Filter for Movie Ids in remote id search (#187) @scampower3
  - Fix IsMatch logic (#188) @scampower3
  - Update all items returned from GetItemList (#178) @scampower3

  ### Code or Repo Maintenance ###
  - Use Named Tuple (#177) @scampower3
  - Remove MaxSearchResults  (#174) @scampower3

  ### Dependency updates ###
  - Update dependency Microsoft.Extensions.Http to 8.0.1 (#181) @renovate
